# Generated by Django 6.0.2 on 2026-02-26 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('ELEC', 'Electrónica y Tecnología'), ('ROPA', 'Ropa y Accesorios'), ('HOGAR', 'Hogar y Muebles'), ('DEPORTE', 'Deportes y Aire Libre'), ('JUEGOS', 'Juguetes y Videojuegos'), ('OTROS', 'Otros')], default='OTROS', max_length=20, verbose_name='Categoría'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
